### PR TITLE
Make top important as to remove hover pulldown

### PR DESCRIPTION
**Pull request by Coding-Hen**
When hovering over a glyphicon question sign on the index page the onhover pulls down the glyphicon and pings back when not

### CODE REVIEW

**Comment by tehhowch** [comment]
I'd much rather we not use the `!important` style override.

**Comment by tsitu** [comment]
The conflicting `top: 1px` declaration from Bootstrap's `.glyphicon` is being [loaded in deferred](https://github.com/mh-community-tools/mh-hunt-helper/blob/master/src/common_footer.php#L3), overriding the `top: 8px` rule in our page-specific `main.css` due to source order.

`!important` might be the cleanest solution in this situation (compared to using IDs or inline styles), and adheres to the sole exception described by [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#The_!important_exception).

**Review by tsitu — DISMISSED** [review]

**Comment by tehhowch** [comment]
Would resolving #138 also resolve this, without needing `!important`?

**Comment by tsitu** [comment]
@DevJackSmith 

Moving the Bootstrap lib to `common_head.php` fixes both #138 and #146 (see performance difference [here](https://github.com/mh-community-tools/mh-hunt-helper/issues/138#issuecomment-752326255))

**Review by DevJackSmith — APPROVED** [review]

**Comment by DevJackSmith** [comment]
good catch!

**Pull request merged**
